services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"